#!/bin/bash

sudo zypper ref
sudo zypper up
sudo rpm --import https://package.perforce.com/perforce.pubkey
sudo zypper ar -n Perforce https://package.perforce.com/yum/rhel/7/x86_64 Perforce
sudo zypper install helix-p4d helix-cli
sudo zypper install zsh
sudo zypper install xterm-bin terminator emacs-x11

if [ ! -x ~/bin/liar ]; then
    curl -L -f https://framagit.org/grumpyf0x48/liar/raw/master/liar > ~/bin/liar
    chmod 755 ~/bin/liar
fi

# liar -l -p "sublime_text" install sublime3 https://download.sublimetext.com/sublime_text_3_build_3207_x64.tar.bz2

liar -l -p "p4v|p4merge|p4admin" install p4v http://ftp.perforce.com/pub/perforce/r18.4/bin.linux26x86_64/p4v.tgz

