#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Jeff Putsch <jdputsch@gmail.com>
#

# Customize to your needs...

# Local Variables:
# mode: sh
# eval: (sh-set-shell "zsh")
# End:

export COLUMNS="120"

export PATH="$PATH:/home/jputsch/apps/acli/10.2.0/linux/7"

##
# Your previous /Users/Jeff.Putsch/.zprofile file was backed up as /Users/Jeff.Putsch/.zprofile.macports-saved_2023-03-05_at_18:49:01
##

# MacPorts Installer addition on 2023-03-05_at_18:49:01: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.

