# .zshrc is sourced on all zsh invocations, so it should be kept as lean as possible.
#
# Set most, if not all, environment variables in .zshenv, which is sourced before .zshrc
# for all zsh invocations.
# 

## Setup fpath, autoload, and compinit
fpath=(
  ${DOTZSH}/functions
  ${DOTZSH}/completions
  $fpath
)
autoload -- ${DOTZSH}/functions/[^_]*(:t)

## Iniitialze completion system
autoload -Uz compinit
compinit

## zstyles - configure completion system
# See https://thevaluable.dev/zsh-completion-guide-examples/ for descriptions of many
# of these settings.
# :completion:<function>:<completer>:<command>:<argument>:<tag>

# Define completers
# zstyle ':completion:*' completer _extensions _complete _approximate
zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate

# Caching the completion
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path "$XDG_CACHE_HOME/zsh/.zcompcache"

# The completion menu
zstyle ':completion:*' menu select 

# Completion formatting, colors and decoration
zstyle ':completion:*:*:*:*:corrections' format '%F{yellow}!- %d (errors: %e) -!%f'
zstyle ':completion:*:*:*:*:descriptions' format '%F{green}-- %d --%f'
zstyle ':completion:*:*:*:*:messages' format ' %F{purple} -- %d --%f'
zstyle ':completion:*:*:*:*:warnings' format ' %F{red}-- no matches found --%f'

# Try case-insensitive completions, 
# See ZSHCOMPWID "completion matching control"
zstyle ':completion:*' matcher-list '' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'r:|[._-.]=** r:|=**' 'l:|=* r:|=*'

zstyle :compinstall filename "$HOME/.zshrc"

## History file configuration
[ -z "$HISTFILE" ] && HISTFILE="$HOME/.zsh_history"
[ "$HISTSIZE" -lt 50000 ] && HISTSIZE=50000
[ "$SAVEHIST" -lt 10000 ] && SAVEHIST=10000

## History command configuration
setopt extended_history       # record timestamp of command in HISTFILE
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups       # ignore duplicated commands history list
setopt hist_ignore_space      # ignore commands that start with space
setopt hist_verify            # show command with history expansion to user before running it
setopt share_history          # share command history data


# Changing/making/removing directory
# setopt auto_pushd
setopt pushd_ignore_dups
setopt pushdminus
unsetopt autocd

#
# Bindkyes
#
# set esc-l to 'down-case-word'
bindkey -e
bindkey -r "^[l"
bindkey "^[l" down-case-word

#
# Functions
#
# Use /usr/sepp/bin/git when on Linux and it is available
if [[ ${OS} = linux ]] && [[ -x /usr/sepp/bin/git ]]; then
    function git() {
        /usr/sepp/bin/git "$@"
    }
fi

## Plugins

# NVM plugin, lazy load nvm, enable nvm completions
export NVM_COMPLETION=true
export NVM_LAZY_LOAD=true
# Optionally enable nvm lazy loading for other commands:
# export NVM_LAZY_LOAD_EXTRA_COMMANDS=('vim')
source ${DOTZSH}/plugins/zsh-nvm/zsh-nvm.plugin.zsh