## Just source .bashrc
## See: https://shreevatsa.wordpress.com/2008/03/30/zshbash-startup-files-loading-order-bashrc-zshrc-etc/
## and: https://superuser.com/questions/1840395/complete-overview-of-bash-and-zsh-startup-files-sourcing-order

[ -f ${HOME}/.bashrc ] && . ${HOME}/.bashrc

. "$HOME/.local/share/../bin/env"
